---

- name: Check /etc/nginx/sites-available existancy
  stat:
    path: "/etc/nginx/sites-available"
  register: nginx_vhosts_dir
  become: no

- name: Copy certificate
  file:
    src: ../files/nginx-selfsigned.crt
    dest: /etc/ssl/certs/nginx-selfsigned.crt
    owner: root
    group: root
    mode: 0644

- name: Copy certificate signature
  file:
    src: ../files/nginx-selfsigned.key
    dest: /etc/ssl/private/nginx-selfsigned.key
    owner: root
    group: root
    mode: 0644

- name: Register CDM app nginx vhost
  template:
    src: ../templates/local.cdm.conf.j2
    dest: "/etc/nginx/sites-enabled/local.cdm.makersboard.me.conf"
    force: yes
  become: yes
  when: nginx_vhosts_dir.stat.isdir is defined and nginx_vhosts_dir.stat.isdir
  notify:
    - restart webserver

- name: Register Front app nginx vhost
  template:
    src: ../templates/local.front.conf.j2
    dest: "/etc/nginx/sites-enabled/local.front.makersboard.me.conf"
    force: yes
  become: yes
  when: nginx_vhosts_dir.stat.isdir is defined and nginx_vhosts_dir.stat.isdir
  notify:
    - restart webserver
