sidus_eav_model:
    families:
        Base:
            instantiable: false
            attributeAsLabel: title
            attributeAsIdentifier: slug
            attributes:
                title:
                    required: true

                slug:
                    type: string_identifier
                    validation_rules:
                        - Regex:
                            pattern: '/^[a-z0-9]+(?:[-\_][a-z0-9]+)*$/'

                workflowStatus:
                    type: choice
                    required: true
                    default: draft
                    form_options:
                        choices:
                            Draft: draft
                            To Validate: to_validate
                            Rejected: rejected
                            Validated: validated
                            Published: published
