sidus_eav_model:
    families:
        Page:
            parent: Base
            attributeAsLabel: title
            attributes:
                content:
                    group: content
                    type: html
                    form_options:
                        tinymce_theme: advanced

                parentPage:
                    group: content
                    type: autocomplete_data_selector
                    options:
                        allowed_families:
                            - Page

                illustration:
                    group: content
                    type: media_browser
                    options:
                        allowed_families:
                            - Image
