sidus_eav_model:
    families:
        Node:
            data_class: MyEML\EAVModelBundle\Entity\Node
            attributeAsLabel: nodeTitle
            attributes:
                nodeTitle:
                    type: string
                    required: true
                    context_mask: '%myeml.context_mask%'
                children:
                    type: data_selector
                    context_mask: '%myeml.context_mask%'
                    multiple: true
                    options:
                        allowed_families:
                            - Node
                        serializer:
                            by_reference: false
                            by_short_reference: false
                    form_options:
                        allow_edit: true
                        allow_add: true
                    group: hierarchy
                parentNodes:
                    type: data_selector
                    multiple: true
                    form_options:
                        disabled: true
                    group: hierarchy
                    context_mask: '%myeml.context_mask%'
                nodeIsRoot:
                    type: switch
                    context_mask: '%myeml.context_mask%'
                    default: false
                    group: hierarchy
                appearInMenu:
                    type: switch
                    default: false
                    group: hierarchy
                    context_mask: '%myeml.context_mask%'
                frontUrl:
                    type: string
                    group: front
                    context_mask: '%myeml.context_mask%'
                nodeRole:
                    type: choice
                    form_options:
                        choices:
                            Page: page
                            Layout Zone: layout_zone
                            Block: block
                    group: front
                    context_mask: '%myeml.context_mask%'
                componentKey:
                    type: string
                    group: front
                    context_mask: '%myeml.context_mask%'
                externalContent:
                    type: string
                    form_type: MyEML\AdminBundle\Form\DrupalConnectorType
                    group: editorial
                    context_mask: '%myeml.context_mask%'
                behaviorSettings:
                    type: data_selector
                    options:
                        allowed_families:
                            - BasicApiWidgetSettings
                    form_options:
                        allow_add: true
                        allow_edit: true
                    group: Settings

