sidus_admin:
    configurations:
        tree:
            controller: '%eav.controller%'
            entity: '%sidus_data_class%'
            prefix: /tree
            actions:
                index:
                    path:     /
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/{id}/edit
                    form_type: '%eav_form.type%'
                clone:
                    path:     /{familyCode}/{id}/clone
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                icon: sitemap
                datagrid: tree
                families:
                    Node: ~
