parameters:
    sidus_data_class: MyEML\EAVModelBundle\Entity\Data
    sidus_value_class: MyEML\EAVModelBundle\Entity\Value
    sidus_eav_model.context.form_type: MyEML\EAVModelBundle\Form\ContextSwitcherType
    sidus_eav_model.context.default_context:
        campus: lyon
        program: master
        locale: fr_FR
        profile: student
sidus_eav_model:
    data_class: '%sidus_data_class%'
    value_class: '%sidus_value_class%'
    serializer_enabled: true

clever_age_eav_manager_user:
    mailer:
        company: Client Company
        from_email: no-reply@client-company.com
        from_name: Client

imports:
    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }
    - { resource: admin.yml }
    - { resource: eav_datagrid.yml }

    # Model configuration, order of files matters
    - { resource: myeml/node.yml }
