sidus_eav_data_grid:
    configurations:
        node:
            family: Node
            filter_config:
                sortable:
                    - id
                fields: []
            columns:
                id:
                    label: '#'
                nodeTitle:
                    template: '%clickable.template%'
                actions:
                    template: '%eav_datagrid.actions%'
            actions:
                create: '%create.button%'
            reset_button:
                attr:
                    data-target: tg_center
