sidus_eav_data_grid:
    configurations:
        base:
            family: Base
            filter_config:
                sortable:
                    - id
                    - createdAt
                    - updatedAt
                fields: []
            columns:
                id:
                    label: '#'
                label:
                    template: '%clickable.template%'
                createdAt: ~
                updatedAt: ~
                actions:
                    template: '%eav_datagrid.actions%'
            actions:
                create: '%create.button%'
            reset_button:
                attr:
                    data-target: tg_center

        # Configuration Example
        page:
            family: Page
            parent: base
            filter_config:
                sortable:
                    - id
                    - title
                    - slug
                    - parentPage
                    - createdAt
                    - updatedAt
                fields:
                    title: ~
                    slug: ~
                    parentPage:
                        type: autocomplete_data
            columns:
                id:
                    label: "#"
                title:
                    template: '%clickable.template%'
                slug: ~
                parentPage: ~
                createdAt: ~
                updatedAt: ~
                actions:
                    template: '%eav_datagrid.actions%'
