services:
    myeml.eav_boolean_filter:
        parent: eavmanager_api_platform.filter.boolean
        arguments:
            -
                nodeIsRoot: ~
        tags:
            - { name: api_platform.filter, id: myeml.eav_boolean }
