imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: model/application.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: '%trusted_proxies%'
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  "%session.handler_id%"
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

services:
    session.memcached:
        class: Memcached
        arguments:
            - '%session_memcached_prefix%'
        calls:
            - [ addServer, [ '%session_memcached_host%', '%session_memcached_port%' ]]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments:
            - '@session.memcached'
            -
                prefix: '%session_memcached_prefix%'
                expiretime: '%session_memcached_expire%'

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - SidusDataGridBundle:Form:fields.html.twig
        - CleverAgeEAVManagerLayoutBundle:Form:form.fields.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles:
        - CleverAgeEAVManagerLayoutBundle
    node: "%node_path%"
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%node_uglifyjs_path%"
        uglifycss:
            bin: "%node_uglifycss_path%"
    assets:
        map1:
            input: "%kernel.root_dir%/../web/assets/jquery/jquery.min.map"
            output: js/jquery.min.map
        src1:
            input: "%kernel.root_dir%/../web/assets/jquery/jquery.js"
            output: js/jquery.js
