module:
  block: 0
  chosen: 0
  chosen_lib: 0
  chosen_test: 0
  config_filter: 0
  config_split: 0
  dblog: 0
  dynamic_page_cache: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  kint: 0
  myeml_cdm_connector: 0
  node: 0
  page_cache: 0
  system: 0
  text: 0
  update: 0
  user: 0
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
